# Generated by Django 6.0.3 on 2026-04-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.CharField(choices=[('ONE', 'One'), ('TWO', 'Two')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'Phd')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
