# Generated by Django 6.0.3 on 2026-04-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_is_headmaster_remove_user_is_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clerk_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
