# Generated by Django 6.0.3 on 2026-04-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_clerk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('HEADMASTER', 'Headmaster'), ('CLERK', 'Clerk')], default='STUDENT', max_length=10),
        ),
    ]
