# Generated by Django 6.0.3 on 2026-04-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('HEADMASTER', 'Headmaster')], default='STUDENT', max_length=10),
        ),
    ]
