# Generated by Django 6.0.3 on 2026-04-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='education',
        ),
    ]
