# Generated by Django 6.0.3 on 2026-04-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(default='empty', upload_to=''),
            preserve_default=False,
        ),
    ]
