# Generated by Django 6.0.3 on 2026-04-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_enrollment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Semester',
            field=models.CharField(choices=[('ONE', 'One'), ('TWO', 'Two')], max_length=10, null=True),
        ),
    ]
