# Generated by Django 6.0.3 on 2026-04-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assignment_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='finalterm_weightage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='midterm_weightage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='quiz_weightage',
            field=models.FloatField(null=True),
        ),
    ]
